function [pdata,nparts] = partSESS2(mtint,pdata)
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
%partSESS2  takes an mtint and a pdata session structure, generates start/end times for parts
% We want to divide a long recording session into partitions or parts, these might be whole
% recording sessions or they might be based on digital keypresses or you might just want the
% whole thing in one long session. In any case this function takes the keypresses and the desired
% method defining each part and kives the start + end time of each so we can separate the data later
%
% USAGE:
%         pdata = partSESS2(mtint,pdata)
%
% INPUT:
%         mtint - mtint structure generated by klustest (contains keypresses)
%         pdata - session structure generated by klustest (contains part_config)
%
% OUTPUT:
%    pdata - same structure as input but fields are added for each part giving the start/end times
%    nparts - the total number of parts
%
% EXAMPLES:
%
% See also: figKEYS klustest readALLDACQDATA

% HISTORY:
% version 1.0.1, Release 24/11/16 created so this functionality could be shared between 2D and 3D functions
% version 1.0.2, Release 01/04/17 changed to a cell array format
% version 1.0.3, Release 06/04/17 changed to a structure format
% version 2.0.0, Release 05/04/19 changed to partSESS2 in klustest update
% version 2.0.1, Release 05/04/19 part times are now stored in pdata, simplified handling of cases
%
% Author: Roddy Grieves
% UCL, 26 Bedford Way
% eMail: r.grieves@ucl.ac.uk
% Copyright 2018 Roddy Grieves

%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
%% INPUT ARGUMENTS CHECK
% deal with input variables
inps = {'mtint','pdata'};
vals = {'1','1'};
reqd = [1 1];
for ff = 1:length(inps)
    if ~exist(inps{ff},'var')
        if reqd(ff)
            error('ERROR: vargin %s missing... exiting',inps{ff});            
        end        
        eval([inps{ff} '=' vals{ff} ';']);
    end
end

%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
%% FUNCTION BODY
partc = pdata.part_config;

%% Get the recording starts and ends
rect = pdata.recording_times; % get the duration of each recording session
rect = [0; rect(:)]; % add a zero value
dvals = cumsum(rect); % calculate cumulative total, this gives the start/end of each session within the combined files
dvals = [dvals circshift(dvals,-1)]; % we want to go from a single vector of end times to a matrix where each row contains a start and end time
dvals = dvals(1:end-1,:); % we don't want the last row because this just represents the end of the last trial

%% Fix keypresses for the whole recording, if they exist
fnames = pdata.part_names;
mths = partc.Method(:);
if any(mths==3)
    [stimes,etimes] = figKEYS(mtint,pdata);
    atimes = [stimes(:) etimes(:)]; % all time start-end pairs in rows
end

%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%% %% Get the times for each part
nparts = numel(pdata.part_config.Part(:));
dindx = [];
for pp = 1:nparts
    part_method = mths(pp);
    
    switch part_method
        case {1} % if the method is whole session
            pdata.(fnames{pp}).times = [min(dvals(:)), max(dvals(:))]; % start time and end time equals start and end of whole file
            pdata.part_config.times(pp) = {[min(dvals(:)), max(dvals(:))]}; % start time and end time equals start and end of whole file
            pdata.part_config.files(pp) = {pdata.session_details.session_names(:)}; % all recordings contribute to this part
            
        case {2} % if the method is recording session
            recvec = partc.Intervals{pp}; % vector specifying which recordings should be included
            if max(recvec) > numel(dvals(:,1))
                disp(sprintf('\t\tERROR: requested recording (%d) is greater than the number of recordings (%d)... skipping',max(recvec),numel(dvals(:,1))));
                continue
            end 
            pdata.(fnames{pp}).times = dvals(recvec(:),:); % start and end times are the start and end times of the requested recording sessions
            pdata.part_config.times(pp) = {dvals(recvec(:),:)}; % start and end times are the start and end times of the requested recording sessions
            pdata.part_config.files(pp) = {pdata.session_details.session_names(recvec)}; % names of recordings contributing to this part      
            
        case {3} % if the method is intervals (keypresses)
            % determine which trials to include
            recvec = partc.Intervals{pp}; % vector specifying which trials should be included
            if isinf(recvec) % if inpvec is infinite just use all trials
                inplog = true(size(stimes));
            elseif max(recvec) > numel(stimes)
                error('ERROR: requested input interval (%d) is greater than the number of input pairs (%d)... exiting',max(recvec),numel(stimes));
            else % normal handling of trials
                inplog = false(size(stimes));
                inplog(recvec) = true;
            end 
            pdata.(fnames{pp}).times = atimes(inplog,:); % start and end times are the start and end times of the requested intervals (defined by keypresses)   
            pdata.part_config.times(pp) = {atimes(inplog,:)}; % start and end times are the start and end times of the requested intervals (defined by keypresses)    
            
            % Eleonore would like the names of the files contributing to each part, so that is added here
            % to do this we check if the start or end of each triel is within each recording session
            % if one trial starts or ends within a recording session, that session is counted as contributing 
            % to the part
            itimes = pdata.part_config.times{pp};
            sess_indx = zeros(length(itimes(:,1)),length(dvals(:,1)));
            for tt = 1:length(itimes(:,1))
                strt = itimes(tt,1);
                endn = itimes(tt,2);
                
                for ss = 1:length(dvals(:,1))
                    if (strt>dvals(ss,1)&&strt<dvals(ss,2)) || (endn>dvals(ss,1)&&endn<dvals(ss,2))
                        sess_indx(tt,ss) = 1;
                    end
                end
            end
            idx = find(sum(sess_indx));
            pdata.part_config.files(pp) = {pdata.session_details.session_names(idx)}; % names of recordings contributing to this part
    end
end






























